package com.walter.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 2): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 2;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        NoteDao.createTable(db, ifNotExists);
        FlightInfoDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        NoteDao.dropTable(db, ifExists);
        FlightInfoDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
//            dropAllTables(db, true);
//            onCreate(db);
            if (1==oldVersion){
                boolean ifNotExists=false;
                FlightInfoDao.createTable(db,ifNotExists);
                db.execSQL("alter table NOTE add WHATCALL text");


            }
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(NoteDao.class);
        registerDaoClass(FlightInfoDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }


    /**
     * private void creatTableMeal(SQLiteDatabase db) {
     db.execSQL("create table if not exists " + MealSchema.TABLE_NAME +
     "(" + MealSchema._ID +
     " integer primary key autoincrement not null," + MealSchema.LCLDPTDATE +
     " text," + MealSchema.FLIGHTNO +
     " text," + MealSchema.ORGCITYAIRP +
     " text," + MealSchema.DSTCITYAIRP +
     " text," + MealSchema.TYPE +
     " text," + MealSchema.NAME +
     " text," + MealSchema.COUNT +
     " text," + MealSchema.RATE +
     " integer," + MealSchema.PICTURE +
     " text," + MealSchema.CLASSNAME +
     " text," + MealSchema.SUPPLYUNIT +
     " text)");
     }
     *
     *db.execSQL("alter table psg_info add upgradeStatus text");
     db.execSQL("drop table meal");
     *
     *
     *
     *
     */
    
}
