package com.walter.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.walter.greendao.Note;
import com.walter.greendao.FlightInfo;

import com.walter.greendao.NoteDao;
import com.walter.greendao.FlightInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig flightInfoDaoConfig;

    private final NoteDao noteDao;
    private final FlightInfoDao flightInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        flightInfoDaoConfig = daoConfigMap.get(FlightInfoDao.class).clone();
        flightInfoDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        flightInfoDao = new FlightInfoDao(flightInfoDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(FlightInfo.class, flightInfoDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        flightInfoDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public FlightInfoDao getFlightInfoDao() {
        return flightInfoDao;
    }

}
