package com.walter.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FLIGHT_INFO".
 */
public class FlightInfo {

    private Long id;
    private String flightNum;

    public FlightInfo() {
    }

    public FlightInfo(Long id) {
        this.id = id;
    }

    public FlightInfo(Long id, String flightNum) {
        this.id = id;
        this.flightNum = flightNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFlightNum() {
        return flightNum;
    }

    public void setFlightNum(String flightNum) {
        this.flightNum = flightNum;
    }

}
